name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Schritt 1: Docker Image bauen
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/vue-app:latest

      # Schritt 2: Logge dich bei Docker Hub ein
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Schritt 3: Docker Image in die Registry pushen
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/vue-app:latest

      # Schritt 4: Trigger Deployment Webhook (optional, wenn Docker Push erfolgreich war)
      - name: Trigger Deployment Webhook
        run: |
          SECRET=${{ secrets.WEBHOOK_SECRET }}
          curl -X POST -H "Authorization: $SECRET" http://193.41.237.94:10000/hooks/deploy
